# Generated by Django 4.1.5 on 2023-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_blog', '0002_posta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posta',
        ),
    ]
