# Generated by Django 4.1.5 on 2023-01-21 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_blog', '0004_post_created_at_post_description_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 19, 37, 48, 918123, tzinfo=datetime.timezone.utc)),
        ),
    ]
