# Generated by Django 4.1.5 on 2023-01-22 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_blog', '0009_delete_users_post_user_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 0, 34, 21, 10351, tzinfo=datetime.timezone.utc)),
        ),
    ]
